# first stage
FROM node:24 AS build

WORKDIR /usr/src/app

COPY ./package*.json ./

# install the needed dependencies
RUN npm install

COPY . .

# create the dist folder
RUN npm run build

# final stage
FROM node:24

WORKDIR /usr/src/app

# using serve as the static server 
RUN npm install -g serve

COPY --from=build /usr/src/app/dist .

EXPOSE 5000

CMD ["serve","--ssl-cert","/etc/letsencrypt/live/feigefiatshamirdemo.ddns.net/fullchain.pem","--ssl-key","/etc/letsencrypt/live/feigefiatshamirdemo.ddns.net/privkey.pem","-s", ".", "-l", "5000"]
