services:
  backend:
    build: ./backend
    ports:
      - "8000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    environment:
      BACKEND_BASE_URL: https://feigefiatshamirdemo.ddns.net:8000
    ports:
      - "443:5000"
    depends_on:
      backend:
        condition: service_started
      # can provide healthcheck in the backend image and provide service_healthy condition check in this image in future
    volumes:
      - type: bind
        source: '/etc/letsencrypt/live/feigefiatshamirdemo.ddns.net/fullchain.pem'
        target: '/etc/letsencrypt/live/feigefiatshamirdemo.ddns.net/fullchain.pem'
      - type: bind
        source: '/etc/letsencrypt/live/feigefiatshamirdemo.ddns.net/privkey.pem'
        target: '/etc/letsencrypt/live/feigefiatshamirdemo.ddns.net/privkey.pem'
